### PR TITLE
Add initial GitHub workflows

### PR DESCRIPTION
**Pull request by jon-tow**
This PR adds initial GitHub workflows for building, testing, and checking for code quality.

### CODE REVIEW

**Comment by jon-tow** [comment]
This relies on #42 for automatic `flake8` dependency installation in the `build.yml` run.

**Comment by jon-tow** [comment]
I've removed the "undefined name" check in the build workflow. CC @cat-state if they think we should add `mypy` in this PR or open a new one when we figure out how to properly set it up.

**Comment by Dahoas** [comment]
If we think `mypy` can be set up by end of the week I'm for adding to this PR. If not we can merge now.

**Comment by LouisCastricato** [comment]
Is this good to merge?

**Comment by cat-state** [comment]
I think let's do mypy on a subsequent one cus we'll have type errors and annotations to fix

**Comment by jon-tow** [comment]
Le'ts merge. I'm currently unfamiliar with `mypy` and Aman might be too busy to add it right now. We can move discussions/concerns to issue #40.

**Pull request merged**
