### PR TITLE
Ppo reward normalization

### PR DESCRIPTION
**Pull request by Dahoas**
This pr implements .generate for the ref branch model. This allows us to normalize the rewards ([important for good ppo performance](https://iclr-blog-track.github.io/2022/03/25/ppo-implementation-details/)) by computing mean and standard deviation statistics for continuations generated by the ref model. 

Note ref model generation at exploration time is expensive. Therefore it is recommended reward mean and standard deviation are computed before hand and passed in via the method config.

Without normalization: [wandb](https://wandb.ai/dahoas/trlx-examples/runs/1nl72iw8/overview?workspace=user-dahoas)
With normalization: [wandb](https://wandb.ai/dahoas/trlx-examples/runs/3t0f4h7s/overview?workspace=user-dahoas)

### CODE REVIEW

**Comment by LouisCastricato** [comment]
Hey can you explain what this PR does? Cite a paper?

**Comment by LouisCastricato** [comment]
Can you post a wandb of this working with and without normalization?

**Comment by Dahoas** [comment]
Ugh how can I tell why I'm failing the style check?

**Comment by LouisCastricato** [comment]
@cat-state how do

**Comment by jon-tow** [comment]
@Dahoas Click on the `Details` link of the Code Quality check.
Screen Shot 2022-10-19 at 6 18 11 PM

You can automate checks locally by running:
```bash
pre-commit run --all-files
```
from the command line (make sure `pre-commit` is installed - it should be if you've   
 run the latest setup and `pip install -e ".[dev]"`). I'll start a contribution guide so others are aware!

**Pull request closed without merging**
