### PR TITLE
[fix] Set deepspeed's fp16 `auto_cast` to false

### PR DESCRIPTION
**Pull request by reciprocated**
Fix of #238 

https://github.com/huggingface/accelerate/blob/4e5cc0c6b9c28fc569bfc70dd0508225d187fbf9/src/accelerate/utils/dataclasses.py#L527

https://wandb.ai/sorry/trlx/reports/-fix-Set-deepspeed-s-fp16-auto_cast-to-false-279--VmlldzozNDkzMzkx

Thanks @ZHAOTING for finding this fix

### CODE REVIEW

**Comment by cat-state** [comment]
Thanks @reciprocated and @ZHAOTING . Does this increa

se memory usage? Or are the model weights still being cast to fp16 somewhere else? I see in the report that the bf16 and fp16 runs have about the same but theres a run which seems to have more memory use:

2023-02-06-142143_738x134_scrot

**Comment by reciprocated** [comment]
No, it doesn't increase the memory usage. For the baseline I took by accident a prior bf16 run, while on the fix is a run without accelerate, so the difference here is between bf16 and fp32 (it's not possible to make a fp16 run on the main). Just in case I made a few more runs with fp32, zero-fp32, zero-fp16, zero-bf16:
https://wandb.ai/sorry/trlx/reports/Set-deepspeed-s-fp16-auto_cast-to-false-279--VmlldzozNDk0OTMz

**Comment by cat-state** [comment]
Ah okay, got it. This LGTM!

**Review by cat-state — APPROVED** [review]

**Comment by reciprocated** [comment]
Hi! @xwwwwww, I'm able to reproduce the first part, it's related to the newest accelerate release which started to raise errors in this case, however I'm not getting the runtime error you're having. Maybe it's related to some particular versioning (at least that's what a quick google search suggests). Are you having the same problem for other examples as well?

**Comment by xwwwwww** [comment]
Hi! @reciprocated 
For the second problem, I fix it as follows:

```
tmp = np.inf * torch.ones_like(xs)
min=torch.where(mask.bool(), xs, tmp).min(),
max=torch.where(mask.bool(), xs, -tmp).max(),
```

and my torch version is 1.10.1

**Comment by PhungVanDuy** [comment]
> 

Can you try to upgrade your pytorch version? ref: https://github.com/CarperAI/trlx/issues/264#issuecomment-1422275089

**Pull request merged**
