### PR TITLE
[feat] Add `batch_size` option for the reward model

### PR DESCRIPTION
**Pull request by maxreciprocate**
This PR add's new config option to control `batch_size` used in `reward_fn`. Needed to make custom configs for different setups with different amount of memory available (80GB, 40GB or even cpu offload).

https://api.wandb.ai/links/sorry/g03gp4g7

### CODE REVIEW

**Comment by cat-state** [comment]
Since this is a configuration item only relevant to the examples and not to the trainers themselves, I'm not sure if it should actually be trlx's concern what batchsize you use for your RM

**Comment by reciprocated** [comment]
I agree this configuration item is not of necessity for trainer (unless we make it so by batching inside the trainer, unlike as currently outside), but it's rather for convenience since it's a reoccurring item, perhaps not deserving to be put into ad-hoc category of using environment variables or argvs for it. Yet I'm not married to this, it's just something that came up with many configs of https://github.com/CarperAI/trlx/pull/128/files

**Comment by LouisCastricato** [comment]
Can we merge or close this

**Comment by Dahoas** [comment]
Same question as @LouisCastricato. I think it makes sense to push batching functionality onto the the `reward_fn` designer, as is done in the [HH example](https://github.com/CarperAI/trlx/blob/404217b2f3f295ff0f68851524517064acc43a15/examples/hh/ppo_hh.py#L170).

**Comment by Dahoas** [comment]
@maxreciprocate are you ok with closing this?

**Comment by maxreciprocate** [comment]
Yeah, I'm closing it

**Pull request closed without merging**
