### PR TITLE
Value branch

### PR DESCRIPTION
**Pull request by Dahoas**
Introduces `num_value_layers_unfrozen` model parameter

### CODE REVIEW

**Comment by Dahoas** [comment]
@PhungVanDuy When you get a chance.

**Comment by PhungVanDuy** [comment]
> @PhungVanDuy When you get a chance.

@Dahoas I am running experiments on HH.

**Comment by PhungVanDuy** [comment]
> > @PhungVanDuy When you get a chance.
> 
> @Dahoas I am running experiments on HH.
The code-based sounds good to me.
It is alright on the HH dataset, run here: https://wandb.ai/pvduy/trlx/runs/mswxa332
Max also running some benchmarks.

**Comment by maxreciprocate** [comment]
I've run benchmark on this PR using `"method": {"num_value_layers_unfrozen": 8}`, comparing against runs from main and I don't see any difference, although I feel like there should be, or maybe I'm setting parameters wrongly/in the wrong combination?

https://wandb.ai/sorry/trlx-references/reports/value-branch-v-main--Vmlldzo0OTY3MDU5

https://wandb.ai/sorry/trlx-references/runs/oqn7fei0?workspace=user-sorry
Screenshot 2023-07-26 at 06 20 38

**Comment by Dahoas** [comment]
When implementing I assumed that `num_layers_unfrozen >= num_value_layers_unfrozen`, though looking back over the code I'm not sure why your combination would result in no change between runs.

**Comment by maxreciprocate** [comment]
Here are the results of the benchmark with updated code https://wandb.ai/sorry/trlx-references/reports/value-branch-v-main--Vmlldzo1MDAxOTA2

Screenshot 2023-07-31 at 11 31 47

**Comment by Dahoas** [comment]
> Here are the results of the benchmark with updated code https://wandb.ai/sorry/trlx-references/reports/value-branch-v-main--Vmlldzo1MDAxOTA2
> 
> Screenshot 2023-07-31 at 11 31 47

Seems to do worse on the randomwalks (any idea why?) task but otherwise gives some small improvements. If there are no other comments do we want to merge?

**Review by maxreciprocate — APPROVED** [review]
LGTM!

@Dahoas regarding randomwalks, it's most likely a hyperparameter issue (the model there is just a 2-layer transformer, so `num_value_layers_unfrozen` was also set to 2 for that example)

**Pull request merged**
