### PR TITLE
Update generation utilities

### PR DESCRIPTION
**Pull request by reciprocated**
This PR will
- [x] enable sweeping over a single `gen_kwargs` value (e.g. `temperature`, `top_k`, `beta`) during periodic evaluations
- [x] change `reward_fn`'s signature from `reward_fn(samples)` to `reward_fn(samples, prompts, responses)`
- [x] add an optional stop keyword to `gen_kwargs` (e.g. Models indicate they have completed a response by generating a stop sequence, which is literally the string "Human:" – from Anthropic's 2021 "A General Language Assistant as a Laboratory for Alignment")
- [x] clean up evaluation result's outputs

Among HF's `generate` arguments `StoppingCriteria` can only stop all generations per batch, `eos_token_ids` accepts only `List[int]`. The other option is to customize `generate` method for every architecture or to trim samples after `generate` as was done here

https://wandb.ai/sorry/trlx/reports/-Update-generation-utilities-172---VmlldzozMzIxMjE1
https://wandb.ai/sorry/trlx/reports/Update-generation-utilities-172--VmlldzozMzIxMjE5

### CODE REVIEW

**Comment by LouisCastricato** [comment]
@PhungVanDuy Are we adding best-of-n here?

**Comment by PhungVanDuy** [comment]
> @PhungVanDuy Are we adding best-of-n here?

Yes, we can add it here.

**Comment by LouisCastricato** [comment]
Are we planning to merge tonight

**Comment by reciprocated** [comment]
No, I still have to update every other example (currently grappling with T5's) and make regression plots. I will also add clarifying comments shortly so until don't rush with reviewing

**Review by jon-tow — CHANGES_REQUESTED** [review]
Very nice update. I've left some comments for feedback. Could you also resolve the merge conflicts when you get a chance? Thanks 🙏

**Review by jon-tow — APPROVED** [review]

**Pull request merged**
