### PR TITLE
Add optional normalization (cont.)

### PR DESCRIPTION
**Pull request by reciprocated**
- change scaling reward to have three options: ref/running/none
- add single thread test of running mean calculations

https://wandb.ai/sorry/public/runs/2x8totg2

### CODE REVIEW

**Comment by Dahoas** [comment]
I just noticed all the unittests are no longer being run upon pr submission. Do we know why?

**Comment by Dahoas** [comment]
Things look good. Can you just provide a way for users to optionally specify a ref_mean and ref_var in the ppo config? You can make them Optional[float] parameters defaulting to false in the PPOMethodConfig

**Comment by Dahoas** [comment]
Also louis will want you to address all his comments from before

**Comment by reciprocated** [comment]
> I just noticed all the unittests are no longer being run upon pr submission. Do we know why?

#92 was the last pr on which unittests ran, I can fix it in this pr
Oh it's about master->main change https://github.com/CarperAI/trlx/blob/12598e9309dd77f772094fc1fab82b7d9e9701de/.github/workflows/build.yml#L7

> Also louis will want you to address all his comments from before

I think I have haven't I, i.e. running var calculation and storing ref_*

**Comment by Dahoas** [comment]
@LouisCastricato Are you happy with the comments?

**Comment by LouisCastricato** [comment]
I think this is ok to merge

**Review by LouisCastricato — APPROVED** [review]

**Pull request merged**
