### PR TITLE
Add isort flake8

### PR DESCRIPTION
**Pull request by cat-state**
TODO: make repo flake8 compatible

### CODE REVIEW

**Comment by cat-state** [comment]
```
trlx/model/__init__.py:112:13: E722 do not use bare 'except'
trlx/model/__init__.py:128:13: E722 do not use bare 'except'
docs/source/conf.py:31:1: F401 'sphinx_rtd_theme' imported but unused
docs/source/conf.py:31:1: E402 module level import not at top of file
docs/source/conf.py:34:9: E126 continuation line over-indented for hanging indent
trlx/model/accelerate_base_model.py:6:1: F401 'torch.nn.functional as F' imported but unused
trlx/model/accelerate_base_model.py:9:1: F401 'torch.utils.data.DataLoader' imported but unused
trlx/model/accelerate_base_model.py:11:1: F401 'transformers.AutoConfig' imported but unused
trlx/model/accelerate_base_model.py:13:1: F401 'trlx.data.BatchElement' imported but unused
trlx/model/accelerate_base_model.py:13:1: F401 'trlx.data.RLElement' imported but unused
trlx/model/accelerate_base_model.py:14:1: F401 'trlx.data.accelerate_base_datatypes.AccelerateRLBatchElement' imported but unused
trlx/model/accelerate_base_model.py:18:1: F401 'trlx.pipeline.accelerate_base_pipeline.AccelerateRolloutStorage' imported but unused
trlx/model/accelerate_base_model.py:19:1: F401 'trlx.utils.Clock' imported but unused
trlx/model/accelerate_base_model.py:19:1: F401 'trlx.utils.rampup_decay' imported but unused
trlx/model/accelerate_base_model.py:19:1: F401 'trlx.utils.safe_mkdir' imported but unused
trlx/model/accelerate_base_model.py:19:1: F401 'trlx.utils.topk_mask' imported but unused
trlx/model/accelerate_base_model.py:130:17: W503 line break before binary operator
trlx/pipeline/__init__.py:1:1: F401 'random' imported but unused
trlx/pipeline/__init__.py:3:1: F401 'abc.abstractstaticmethod' imported but unused
trlx/pipeline/__init__.py:6:1: F401 'datasets.load_from_disk' imported but unused
trlx/data/ilql_types.py:2:1: F401 'typing.Callable' imported but unused
trlx/data/ilql_types.py:2:1: F401 'typing.Iterable' imported but unused
trlx/model/accelerate_ppo_model.py:1:1: F401 'os' imported but unused
trlx/model/accelerate_ppo_model.py:2:1: F401 'abc.abstractmethod' imported but unused
trlx/model/accelerate_ppo_model.py:3:1: F401 'typing.Dict' imported but unused
trlx/model/accelerate_ppo_model.py:3:1: F401 'typing.Iterable' imported but unused
trlx/model/accelerate_ppo_model.py:3:1: F401 'typing.Tuple' imported but unused
trlx/model/accelerate_ppo_model.py:7:1: F401 'torch.nn.functional as F' imported but unused
trlx/model/accelerate_ppo_model.py:9:1: F401 'accelerate.Accelerator' imported but unused
trlx/model/accelerate_ppo_model.py:10:1: F401 'torch.utils.data.DataLoader' imported but unused
trlx/model/accelerate_ppo_model.py:11:1: F401 'torchtyping.TensorType' imported but unused
trlx/model/accelerate_ppo_model.py:12:1: F401 'tqdm.tqdm' imported but unused
trlx/model/accelerate_ppo_model.py:13:1: F401 'transformers.AutoConfig' imported but unused
trlx/model/accelerate_ppo_model.py:13:1: F401 'transformers.AutoTokenizer' imported but unused
trlx/model/accelerate_ppo_model.py:17:1: F401 'trlx.model.BaseRLModel' imported but unused
trlx/model/accelerate_ppo_model.py:19:1: F401 'trlx.model.nn.ppo_models.GPTHeadWithValueModel' imported but unused
trlx/model/accelerate_ppo_model.py:22:1: F401 'trlx.utils.Clock' imported but unused
trlx/model/accelerate_ppo_model.py:22:1: F401 'trlx.utils.rampup_decay' imported but unused
trlx/model/accelerate_ppo_model.py:22:1: F401 'trlx.utils.safe_mkdir' imported but unused
trlx/model/accelerate_ppo_model.py:22:1: F401 'trlx.utils.topk_mask' imported but unused
trlx/model/accelerate_ppo_model.py:81:17: W503 line break before binary operator
trlx/model/accelerate_ppo_model.py:82:17: W503 line break before binary operator
trlx/model/accelerate_ppo_model.py:144:17: W503 line break before binary operator
trlx/model/accelerate_ppo_model.py:186:13: W503 line break before binary operator
trlx/model/nn/ilql_models.py:5:1: F401 'typing.NamedTuple' imported but unused
trlx/model/nn/ilql_models.py:5:1: F401 'typing.Tuple' imported but unused
trlx/model/nn/ilql_models.py:7:1: F401 'accelerate' imported but unused
trlx/model/nn/ilql_models.py:13:1: F401 'accelerate.utils.compute_module_sizes' imported but unused
trlx/model/nn/ilql_models.py:14:1: F401 'torch.tensor' imported but unused
trlx/model/nn/ilql_models.py:15:1: F401 'transformers.AutoConfig' imported but unused
trlx/model/nn/ilql_models.py:41:17: F841 local variable '_hfconfig' is assigned to but never used
trlx/model/nn/ilql_models.py:138:17: W503 line break before binary operator
trlx/model/nn/ilql_models.py:140:13: W503 line break before binary operator
trlx/model/nn/ilql_models.py:150:17: W503 line break before binary operator
trlx/model/nn/ilql_models.py:158:17: W503 line break before binary operator
trlx/model/nn/ilql_models.py:166:17: W503 line break before binary operator
trlx/model/nn/ilql_models.py:173:13: W503 line break before binary operator
trlx/data/method_configs.py:3:1: F401 'typing.Optional' imported but unused
trlx/data/method_configs.py:5:1: F401 'yaml' imported but unused
trlx/pipeline/ppo_pipeline.py:1:1: F401 'functools.partial' imported but unused
trlx/pipeline/ppo_pipeline.py:1:1: F401 'functools.reduce' imported but unused
trlx/pipeline/ppo_pipeline.py:2:1: F401 'typing.Tuple' imported but unused
trlx/pipeline/ppo_pipeline.py:7:1: F401 'torchtyping.TensorType' imported but unused
trlx/pipeline/accelerate_base_pipeline.py:1:1: F401 'functools.partial' imported but unused
trlx/pipeline/accelerate_base_pipeline.py:1:1: F401 'functools.reduce' imported but unused
trlx/pipeline/accelerate_base_pipeline.py:5:1: F401 'datasets.load_dataset' imported but unused
trlx/pipeline/accelerate_base_pipeline.py:9:1: F401 'trlx.data.accelerate_base_datatypes.AccelerateRLBatchElement' imported but unused
trlx/data/__init__.py:1:1: F401 'random' imported but unused
trlx/data/__init__.py:3:1: F401 'typing.Callable' imported but unused
trlx/data/__init__.py:3:1: F401 'typing.List' imported but unused
examples/ilql_randomwalks.py:4:1: F401 'transformers.AutoModel' imported but unused
examples/ilql_randomwalks.py:4:1: F401 'transformers.AutoTokenizer' imported but unused
examples/ilql_randomwalks.py:56:9: E722 do not use bare 'except'
unittests/test_ppo.py:4:1: F401 'transformers.AutoConfig' imported but unused
unittests/test_ppo.py:7:1: F401 'trlx.model.accelerate_ppo_model.AcceleratePPOModel' imported but unused
unittests/test_ppo.py:8:1: F401 'trlx.model.nn.ppo_models.GPTHeadWithValueModel' imported but unused
unittests/test_ppo.py:10:1: F401 'trlx.orchestrator.ppo_orchestrator.PPOOrchestrator' imported but unused
unittests/test_ppo.py:11:1: F401 'trlx.pipeline.ppo_pipeline.PPOPipeline' imported but unused
unittests/test_ppo.py:12:1: F401 'trlx.utils.loading.get_model' imported but unused
unittests/test_ppo.py:12:1: F401 'trlx.utils.loading.get_orchestrator' imported but unused
unittests/test_ppo.py:12:1: F401 'trlx.utils.loading.get_pipeline' imported but unused
trlx/pipeline/offline_pipeline.py:1:1: F401 'typing.Callable' imported but unused
trlx/pipeline/offline_pipeline.py:1:1: F401 'typing.Tuple' imported but unused
trlx/pipeline/offline_pipeline.py:3:1: F401 'torch' imported but unused
trlx/pipeline/offline_pipeline.py:4:1: F401 'datasets.load_dataset' imported but unused
trlx/pipeline/offline_pipeline.py:7:1: F401 'torchtyping.TensorType' imported but unused
examples/ilql_sentiments.py:1:1: F401 'math' imported but unused
examples/ilql_sentiments.py:4:1: F401 'numpy as np' imported but unused
trlx/model/accelerate_ilql_model.py:2:1: F401 'typing.Iterable' imported but unused
trlx/model/accelerate_ilql_model.py:4:1: F401 'numpy as np' imported but unused
trlx/model/accelerate_ilql_model.py:6:1: F401 'torch.nn.functional as F' imported but unused
trlx/model/accelerate_ilql_model.py:9:1: F401 'torch.utils.data.DataLoader' imported but unused
trlx/model/accelerate_ilql_model.py:10:1: F401 'transformers.AutoConfig' imported but unused
trlx/model/accelerate_ilql_model.py:10:1: F401 'transformers.AutoTokenizer' imported but unused
trlx/model/accelerate_ilql_model.py:14:1: F401 'trlx.pipeline.offline_pipeline.OfflinePipeline' imported but unused
trlx/model/accelerate_ilql_model.py:14:1: F401 'trlx.pipeline.offline_pipeline.OfflineRolloutStorage' imported but unused
trlx/model/accelerate_ilql_model.py:16:1: F401 'trlx.utils.safe_mkdir' imported but unused
trlx/model/accelerate_ilql_model.py:16:1: F401 'trlx.utils.topk_mask' imported but unused
trlx/model/accelerate_ilql_model.py:63:17: W503 line break before binary operator
trlx/model/accelerate_ilql_model.py:85:9: F841 local variable 'timer' is assigned to but never used
trlx/model/accelerate_ilql_model.py:106:13: F841 local variable 'evals_stats' is assigned to but never used
trlx/model/accelerate_ilql_model.py:144:37: F541 f-string is missing placeholders
trlx/model/nn/ppo_models.py:7:1: F401 'torch.nn.functional as F' imported but unused
trlx/model/nn/ppo_models.py:9:1: F401 'torch.nn.Identity' imported but unused
trlx/model/nn/ppo_models.py:10:1: F401 'transformers.GPT2LMHeadModel' imported but unused
trlx/model/nn/ppo_models.py:10:1: F401 'transformers.GPT2Model' imported but unused
trlx/model/nn/ppo_models.py:10:1: F401 'transformers.GPT2PreTrainedModel' imported but unused
trlx/model/nn/ppo_models.py:10:1: F401 'transformers.GPT2Tokenizer' imported but unused
trlx/model/nn/ppo_models.py:10:1: F401 'transformers.GPTJModel' imported but unused
trlx/model/nn/ppo_models.py:10:1: F401 'transformers.top_k_top_p_filtering' imported but unused
trlx/model/nn/ppo_models.py:180:13: F841 local variable 'past_length' is assigned to but never used
trlx/model/nn/ppo_models.py:302:9: E266 too many leading '#' for block comment
trlx/data/configs.py:1:1: F401 'sys' imported but unused
trlx/data/configs.py:3:1: F401 'typing.Callable' imported but unused
trlx/data/configs.py:3:1: F401 'typing.Optional' imported but unused
trlx/orchestrator/ppo_orchestrator.py:4:1: F401 'wandb' imported but unused
trlx/orchestrator/ppo_orchestrator.py:5:1: F401 'tqdm.tqdm' imported but unused
trlx/orchestrator/ppo_orchestrator.py:6:1: F401 'transformers.pipeline as tfpipeline' imported but unused
trlx/orchestrator/ppo_orchestrator.py:11:1: F401 'trlx.model.nn.ppo_models.GPTHeadWithValueModel' imported but unused
trlx/orchestrator/ppo_orchestrator.py:11:1: F401 'trlx.model.nn.ppo_models.GPTHydraHeadWithValueModel' imported but unused
trlx/orchestrator/ppo_orchestrator.py:15:1: F401 'trlx.utils.chunk' imported but unused
trlx/orchestrator/ppo_orchestrator.py:15:1: F401 'trlx.utils.flatten' imported but unused
trlx/orchestrator/ppo_orchestrator.py:15:1: F401 'trlx.utils.sentiment_score' imported but unused
trlx/data/ppo_types.py:2:1: F401 'typing.Callable' imported but unused
trlx/data/ppo_types.py:2:1: F401 'typing.Iterable' imported but unused
trlx/data/ppo_types.py:4:1: F401 'torch' imported but unused
trlx/data/accelerate_base_datatypes.py:2:1: F401 'typing.Callable' imported but unused
trlx/data/accelerate_base_datatypes.py:4:1: F401 'torch' imported but unused
```

**Comment by cat-state** [comment]
Should merge https://github.com/CarperAI/trlx/pull/24 first as most of the errors re in files touched by it

**Comment by LouisCastricato** [comment]
What are we doing with this PR

**Comment by LouisCastricato** [comment]
Following up

**Comment by LouisCastricato** [comment]
Closing?

**Pull request closed without merging**
