### PR TITLE
Make on-the-fly configs work with HPTHydraHeadWithValueModel

### PR DESCRIPTION
**Pull request by dpaleka**

### CODE REVIEW

**Comment by LouisCastricato** [comment]
Are we planning to merge this @reciprocated

**Comment by reciprocated** [comment]
I think @jon-tow should be the judge, since it maybe overlaps with his work in
- #103

**Comment by jon-tow** [comment]
Hey @dpaleka ! Thanks for submitting a PR. This functionality should be covered in the PR linked by `@reciprocated` above. Specifically, see the following lines [here](https://github.com/CarperAI/trlx/blob/a526c8dc688e354a641d78982e8822b459d69d15/trlx/model/nn/ppo_models.py#L302=L308). Let me know if this doesn't match your needs 🙏

**Comment by dpaleka** [comment]
resolved in another PR

**Pull request closed without merging**
