### PR TITLE
Save strategy

### PR DESCRIPTION
**Pull request by odellus**
Simple implementation of a step based save strategy as discussed in issue #17

### CODE REVIEW

**Comment by LouisCastricato** [comment]
https://github.com/CarperAI/trlx/pull/24 Can you make your PR work off of this branch?

**Comment by odellus** [comment]
Rebased off of stage-api branch. Do you want to just merge into stage-api and then you folks can merge further from there?

**Comment by LouisCastricato** [comment]
Sounds good. @reciprocated

**Comment by reciprocated** [comment]
looks alright, much appreciated!

**Pull request merged**
