### PR TITLE
[feat] Add LLaMa Model support for PPO

### PR DESCRIPTION
**Pull request by PhungVanDuy**
Add LLaMa Model to trlx this PR handling with PPO algorithm

Wandb sentiment: https://wandb.ai/pvduy/trlx/runs/rtyfu6tb?workspace=user-pvduy

### CODE REVIEW

**Comment by PhungVanDuy** [comment]
> @PhungVanDuy any idea when will this be merged to main?

Thank you for your interested in this. Actually, it is ready to merge already but needs to review by others, will merge it shortly Feel free to use this PR.

**Review by jon-tow — APPROVED** [review]
Great work @PhungVanDuy! 🦙 🚀

**Comment by CSerxy** [comment]
Hi @PhungVanDuy thanks for merging llama support!

Is it possible to provide a demo code for llama fine-tuning with PPO? Many thanks!

**Comment by PhungVanDuy** [comment]
> Hi @PhungVanDuy thanks for merging llama support!
> 
> Is it possible to provide a demo code for llama fine-tuning with PPO? Many thanks!


Thank you for your interest in trlX. Have you tried with the PPO sentiment example [here](https://github.com/CarperAI/trlx/blob/main/examples/ppo_sentiments_llama.py) (replace the model path with LLaMA 2)? 
This is my [run](https://wandb.ai/pvduy/trlx/runs/04m8pfvy/logs?workspace=user-pvduy) recently with LLaMA 2 7B.

**Comment by CSerxy** [comment]
Hi @PhungVanDuy

Thanks for your quick reply! I am trying it this using your example but met some issues. Have you met below problem before?
image

**Comment by CSerxy** [comment]
Besides, I would be sincerely appreciate it if you could share your accelerate/default_config.yaml to me. I doubt if I set something wrong for training.

**Comment by PhungVanDuy** [comment]
> Besides, I would be sincerely appreciate it if you could share your accelerate/default_config.yaml to me. I doubt if I set something wrong for training.

I made this PR: https://github.com/CarperAI/trlx/pull/539
Hope it could help you.

Accelerate configure file you can find at [this](https://github.com/CarperAI/trlx/tree/main/configs/accelerate)

**Comment by CSerxy** [comment]
That's very helpful! I fixed the issue by installing sentencepiece

**Pull request merged**
