### PR TITLE
Create publish_to_pip.yml

### PR DESCRIPTION
**Pull request by BirgerMoell**
Made a build script for publishing the package to python. The script assumes that there is a secrets.PYPI_KEY that contains your key for publishing to pip.

### CODE REVIEW

**Comment by alan-cooney** [comment]
This relates to https://github.com/CarperAI/trlx/issues/199

@BirgerMoell the way I was going to set this up (in a PR) was so that the maintainers can simply create a GitHub release (with the desired version) and then the action can publish to PyPi with that version. You can see an example of this at https://github.com/neelnanda-io/TransformerLens/blob/main/.github/workflows/release.yml (where it also calls the checks workflow before doing this). What do you think about adding this in as well?

**Comment by BirgerMoell** [comment]
I updated the code, I'm not 100% sure if that would automatically run when you publish since I haven't run github actions on publish before, but it would be a minor change to get it to work.

If you set up an account on pypi maybe you could try it out? @alan-cooney

**Comment by alan-cooney** [comment]
I'm not a maintainer so I can't try directly I'm afraid - just making the suggestion above as I was going to pull this off with issue #199. You could however test this on a fork using your own test pypi account - https://test.pypi.org/

The action here wouldn't work exactly - as it doesn't set the version based on the GitHub release version. It also doesn't run the test workflow.

For what it's worth I think you can just copy https://github.com/neelnanda-io/TransformerLens/blob/main/.github/workflows/release.yml exactly and then:

- Replace poetry with pip
- Find something that set the version programatically (to replace `poetry version x`)
- Link to the checks workflow here to run that first

Happy to help do this if you want btw - I just don't use pip anymore as it creates too many headaches with package dependency conflicts when maintaining libs (because it doesn't check for them).

**Comment by cat-state** [comment]
Thanks for this PR! I'll try this out now. One issue with the current packaging (if you `pip install git+github.com...`) is that it doesn't include the examples or configs, but all our examples use them as a base. This might make it not possible to follow the examples when using trlx as a library, so first we should probably inline the configs as classes into the library

**Pull request closed without merging**
